### ISSUE TITLE
Base: add `/@dtag` feature

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-2.0-cosmos#428] opened 2021-10-04 20:37 UTC

**Comment by ryuash** [comment] 2021-10-05 00:56
Duplicate of #133 and #132

**Comment by ryuash** [comment] 2021-10-12 04:45
@Rooty2020 Can you assign someone to design this new page?

**Comment by Rooty2020** [comment] 2021-10-12 12:17
@ryuash 
Sure.
I need to arrange design recourses next week

**Comment by ryuash** [comment] 2021-11-03 00:21
@yayay927 

Task 1: 
We will be displaying profile pages as `/@forbole` `/@kwun` and so on. Create a new page that will load this page if the parameter given starts with `@`. Return to `/` if profiles is not enabled or the parameter does not start with `@`.

Task 2:
Enable search by dtag in the global search bar that directs to the profile screen. Throw an error `profiles not enabled for this explorer` if search starts with `@` but profile is not enabled.

**Comment by yayay927** [comment] 2021-11-03 02:23
@ryuash Okay.

**Closed** 2021-11-29 12:12 UTC
Labels: base
