### ISSUE TITLE
Load-balanced Explorers Do Not Load Properly (NGINX)

### ISSUE THREAD

**Issue by lightiv** [forbole/big-dipper-2.0-cosmos#381] opened 2021-09-27 01:29 UTC
Load-balancing Big-Dipper 2.0

I have ran into an issue where the initial splash screen presents but then the site does not continue to load.  I verified this by proxying two instances of JunoScan and then two other Big Dipper 2.0 explorers which exhibit the same issue.  If you keep hitting refresh you will see the splash screen switch between, Gravity Bridge and Desmos:

https://junoonakash.skynetexplorers.com/

**Comment by rav-11** [comment] 2021-09-27 03:43
Hi @lightiv, please can you share your nginx version and config?

**Comment by rav-11** [comment] 2021-09-28 06:32
I am unable to reproduce this issue with this config/version. We have multiple instances of big dipper running behind nginx proxies with similar configs and do not see this on any of them. In browser dev tools I can see some 404s on js scripts which I think are related, think the cause is probably related to your build or local to your setup so will close this issue.

**Closed by rav-11** 2021-09-28 06:32 UTC

**Comment by lightiv** [comment] 2021-09-28 16:12
Thanks
