### ISSUE TITLE
Evmos: Validator avatar not getting updated

### ISSUE THREAD

**Issue by prajjwol** [forbole/big-dipper-2.0-cosmos#569] opened 2021-11-30 22:30 UTC
We are running into an issue which seems similar to https://github.com/forbole/big-dipper/issues/567

**Comment by ryuash** [comment] 2021-12-01 00:43
@prajjwol Can I get more context/ steps to reproduce?

**Comment by ryuash** [comment] 2021-12-01 00:46
@prajjwol you said the issue was similar but can I get the specific context? 
Unless your api is also https://explore.fetch.ai/validator/fetchvaloper1q77f2plk5ay34gu2y7v5pdj8wxcmrr54n8wnw0

**Comment by DDeAlmeida** [comment] 2021-12-01 07:53
Hi, some news about this issue ?

**Comment by ryuash** [comment] 2021-12-01 08:12
> Hi, some news about this issue ?

@DDeAlmeida 
https://github.com/forbole/big-dipper has been archived and is no longer being maintained so unfortunately no. I believe this is not an issue on big dipper 2.0 ui (this repo) though. Just waiting for @prajjwol to give me specifics so I can confirm if this is a bug in 2.0 or not

**Comment by prajjwol** [comment] 2021-12-01 15:20
@ryuash this is the validator whose icon is not getting updated: https://explorer.evmos.org/validators/evmosvaloper1gxu7cs3hsry3w6506qse9c94vrakllx2jlqh7h

`$ evmosd q staking validator evmosvaloper1gxu7cs3hsry3w6506qse9c94vrakllx2jlqh7h -o json | jq .description`

```{
  "moniker": "Bison Trails",
  "identity": "A296556FF603197C",
  "website": "https://bisontrails.co",
  "security_contact": "https://bisontrails.co",
  "details": "Bison Trails is the easiest way to run infrastructure on multiple blockchains."
}```

**Comment by prajjwol** [comment] 2021-12-01 15:32
@ryuash sorry about the confusion; looks like an issue on our side.

**Comment by DDeAlmeida** [comment] 2021-12-01 15:48
If this is a problem on your side, why did you close it ?
Maybe fix it, link it then close this one..

**Comment by prajjwol** [comment] 2021-12-01 16:17
@DDeAlmeida there was no fix for me to link to unfortunately. Just needed the indexing to finish.

**Comment by prajjwol** [comment] 2021-12-01 16:21
you're right! let me verify my hunch before I close this.

**Comment by ryuash** [comment] 2021-12-02 02:31
Please don't delete any useful context 😅 .

Since we are not the official maintainers for the Evmos explorer I have tested this on another explorer that we maintain. As shown below, I cannot reproduce this issue:

**Create validator with no identity**
https://morpheus.desmos.network/transactions/252B0947ECF6402822A1DBEBE33251734D5C13CDF8B95B69548A1C898E2330E4

```

{
  "operator_address": "desmosvaloper1lxn4ynsp44lepdrutsklmlcxxpry6j0mw27lqq",
  "consensus_pubkey": {
    "@type": "/cosmos.crypto.ed25519.PubKey",
    "key": "cjVVNgo5P5dAILPzV98XXM+m+gqqkIZhHpqWmesvNJg="
  },
  "jailed": false,
  "status": "BOND_STATUS_BONDED",
  "tokens": "1000000",
  "delegator_shares": "1000000.000000000000000000",
  "description": {
    "moniker": "Keybase test",
    "identity": "",
    "website": "",
    "security_contact": "",
    "details": ""
  },
  "unbonding_height": "0",
  "unbonding_time": "1970-01-01T00:00:00Z",
  "commission": {
    "commission_rates": {
      "rate": "0.100000000000000000",
      "max_rate": "1.000000000000000000",
      "max_change_rate": "1.000000000000000000"
    },
    "update_time": "2021-12-02T02:16:20.715772429Z"
  },
  "min_self_delegation": "1"
}
```

![image](https://user-images.githubusercontent.com/42913823/144346075-753fc969-3f9e-4a1b-8a77-22c416bd4312.png)



**Edit Validator**
https://morpheus.desmos.network/transactions/E4E084A19CFB9BC1978738F8527C1883AF136E14EB163DDF2A5F8EFC1C1C9B05

```

{
  "operator_address": "desmosvaloper1lxn4ynsp44lepdrutsklmlcxxpry6j0mw27lqq",
  "consensus_pubkey": {
    "@type": "/cosmos.crypto.ed25519.PubKey",
    "key": "cjVVNgo5P5dAILPzV98XXM+m+gqqkIZhHpqWmesvNJg="
  },
  "jailed": false,
  "status": "BOND_STATUS_BONDED",
  "tokens": "1000000",
  "delegator_shares": "1000000.000000000000000000",
  "description": {
    "moniker": "Keybase test",
    "identity": "2861F5EE06627224",
    "website": "",
    "security_contact": "",
    "details": ""
  },
  "unbonding_height": "0",
  "unbonding_time": "1970-01-01T00:00:00Z",
  "commission": {
    "commission_rates": {
      "rate": "0.100000000000000000",
      "max_rate": "1.000000000000000000",
      "max_change_rate": "1.000000000000000000"
    },
    "update_time": "2021-12-02T02:16:20.715772429Z"
  },
  "min_self_delegation": "1"
}
```
![image](https://user-images.githubusercontent.com/42913823/144346164-d51d31df-5241-46f3-87fd-8b60ade4689b.png)

I would suggest reporting this to the Evmos team (or whoever is maintaining the explorer) on discord as it's most likely an issue with their config/ setup

**Closed** 2021-12-07 02:18 UTC
Labels: chains/others

**Comment by DDeAlmeida** [comment] 2021-12-07 07:38
Hello, i don't understand why did you closed it.
Ok you didin't reproduce one your first test.
But my logo isn't show as expected https://explore.fetch.ai/validator/fetchvaloper1q77f2plk5ay34gu2y7v5pdj8wxcmrr54n8wnw0

**Comment by ryuash** [comment] 2021-12-07 07:46
@DDeAlmeida it was closed due to inactivity and inability to reproduce the same bug.

Fetch.ai's explorer uses the original [Big Dipper](https://github.com/forbole/big-dipper) that is now archived and is not related to this repo.

As we are not the maintainers for Fetch.ai's explorer this is not something we can fix directly. Please contact their team
